export const OPEN_CART_MODAL = "OPEN_CART_MODAL";
export const OPEN_FAVORITES_MODAL = "OPEN_FAVORITES_MODAL";
export const CLOSE_CART_MODAL = "CLOSE_CART_MODAL";
export const CLOSE_FAVORITES_MODAL = "CLOSE_FAVORITES_MODAL";
